refact executeCallback to avoid this
BananaDeveloper/formJS pull request #5
Opened 2019-11-07 14:46 UTC by BananaDeveloper

Refactored executeCallback function to avoid using this.

Updated functions that use executeCallback.

Added a sample test file. You can expand it.

2019-11-11 10:29 UTC, SimplySayHi requested changes
function(s) passed to executeCallback must run with the form instance as context.
It can be useful to set the context for all the functions ( onValidation, beforeSubmit, etc ) directly inside the constructor so that we don't have to add it in multiple files.

2019-11-11 11:24 UTC, BananaDeveloper commented
> function(s) passed to executeCallback must run with the form instance as context.
> It can be useful to set the context for all the functions ( onValidation, beforeSubmit, etc ) directly inside the constructor so that we don't have to add it in multiple files.

Done! 
I am bidning context ony for the options that are passed to executCallback. 
If any other options must be bound please send me a complete list.

2019-11-11 17:09 UTC, SimplySayHi approved these changes

2019-11-12 10:00 UTC, BananaDeveloper commented
@SimplySayHi thanks for the fixes :smile:

2019-11-12 10:00 UTC, merged